# Generated by Django 5.2.4 on 2026-04-19 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RateLimiterState',
            fields=[
                ('bucket_name', models.CharField(choices=[('per_second', 'Per Second'), ('per_minute', 'Per Minute'), ('per_hour', 'Per Hour')], max_length=20, primary_key=True, serialize=False, unique=True)),
                ('tokens_remaining', models.FloatField()),
                ('last_refill_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'rate_limiter_state',
            },
        ),
        migrations.CreateModel(
            name='Scheme',
            fields=[
                ('scheme_code', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('scheme_name', models.CharField(max_length=255)),
                ('amc', models.CharField(choices=[('axis', 'Axis Mutual Fund'), ('hdfc', 'HDFC Mutual Fund'), ('icici', 'ICICI Prudential Mutual Fund'), ('sbi', 'SBI Mutual Fund'), ('kotak', 'Kotak Mahindra Mutual Fund')], max_length=20)),
                ('category', models.CharField(choices=[('midcap', 'Equity: Mid Cap Direct Growth'), ('smallcap', 'Equity: Small Cap Direct Growth')], max_length=20)),
                ('isin', models.CharField(blank=True, max_length=20, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'scheme',
            },
        ),
        migrations.CreateModel(
            name='SyncState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('backfill_done', models.BooleanField(default=False)),
                ('oldest_date', models.DateField(blank=True, null=True)),
                ('latest_date', models.DateField(blank=True, null=True)),
                ('nav_count', models.IntegerField(default=0)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('scheme', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sync_state', to='funds.scheme')),
            ],
            options={
                'db_table': 'sync_state',
            },
        ),
        migrations.CreateModel(
            name='NAVData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('nav', models.DecimalField(decimal_places=4, max_digits=12)),
                ('scheme', models.ForeignKey(db_column='scheme_code', on_delete=django.db.models.deletion.CASCADE, related_name='nav_records', to='funds.scheme')),
            ],
            options={
                'db_table': 'nav_data',
                'indexes': [models.Index(fields=['scheme', 'date'], name='nav_data_scheme__3699e7_idx'), models.Index(fields=['date'], name='nav_data_date_f8ec91_idx')],
                'unique_together': {('scheme', 'date')},
            },
        ),
    ]
