# Generated by Django 5.2.4 on 2026-04-19 11:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheme',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
