# Generated by Django 5.2.4 on 2026-04-19 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0002_alter_scheme_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('window', models.CharField(choices=[('1Y', '1 Year'), ('3Y', '3 Years'), ('5Y', '5 Years'), ('10Y', '10 Years')], max_length=5)),
                ('rolling_min', models.FloatField(null=True)),
                ('rolling_max', models.FloatField(null=True)),
                ('rolling_median', models.FloatField(null=True)),
                ('rolling_p25', models.FloatField(null=True)),
                ('rolling_p75', models.FloatField(null=True)),
                ('max_drawdown', models.FloatField(null=True)),
                ('cagr_min', models.FloatField(null=True)),
                ('cagr_max', models.FloatField(null=True)),
                ('cagr_median', models.FloatField(null=True)),
                ('data_start', models.DateField(null=True)),
                ('data_end', models.DateField(null=True)),
                ('total_days', models.IntegerField(null=True)),
                ('nav_points', models.IntegerField(null=True)),
                ('periods_analyzed', models.IntegerField(null=True)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='funds.scheme')),
            ],
            options={
                'db_table': 'analytics',
                'indexes': [models.Index(fields=['scheme', 'window'], name='analytics_scheme__bccb94_idx'), models.Index(fields=['window', 'rolling_median'], name='analytics_window_15b826_idx')],
                'unique_together': {('scheme', 'window')},
            },
        ),
    ]
